server:
  port: 8686


spring:
  kafka:
    bootstrap-servers: 172.20.10.8:9092,172.20.10.9:9092,172.20.10.10:9092
    producer:
      # 消息发送次数
      retries: 0
      # 一个批次可以使用的内存大小：
      batch-size: 16384
      # 设置生产者内存缓存大小：
      buffer-memory: 33554432
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      group-id:
      # 自动提交的时间间隔： 在spring boot 2.x 版本是值的类型为 Duration 需要符合特定的格式，如1S，1M，2H，5D
      auto-commit-interval: 1S
      # 该属性指定了消费者在读取一个没有偏移的分区或者偏移量无效的情况下该作何处理：
      # earliest:当各分区下有已提交的offset时，从提交的offset开始消费；无提交的offset时，从头开始消费
      # latest:当各分区下有已提交的offset时，从提交的offset开始消费；无提交的offset时，消费新产生的该分区下的数据
      # none:topic各分区都存在已提交的offset时，从offset后开始消费；只要有一个分区不存在已提交的offset，则抛出异常
      auto-offset-reset: earliest
      # 是否自动提交偏移量，默认值为true ,为了避免出现重复数据和数据丢失，可以把他设置为 false,然后手动提交偏移量
      enable-auto-commmit: false